function(anime_vault_apply_sanitizers target)
  get_target_property(target_type ${target} TYPE)

  if(MSVC)
    if(ENABLE_UBSAN)
      message(FATAL_ERROR "UndefinedBehaviorSanitizer is unavailable with MSVC")
    endif()
    if(ENABLE_ASAN)
      if(POLICY CMP0184)
        cmake_policy(GET CMP0184 runtime_checks_policy)
      endif()
      if(runtime_checks_policy STREQUAL "NEW")
        set_property(TARGET ${target} PROPERTY MSVC_RUNTIME_CHECKS "")
      else()
        # CMake 3.x puts /RTC1 in Debug flags; disable those checks per target.
        target_compile_options(${target} PRIVATE
          "/FI${CMAKE_CURRENT_FUNCTION_LIST_DIR}/DisableRuntimeChecks.hpp")
      endif()
      target_compile_options(${target} PRIVATE /fsanitize=address /Zi)
      if(NOT target_type STREQUAL "STATIC_LIBRARY")
        target_link_options(${target} PRIVATE /INCREMENTAL:NO /DEBUG)
      endif()
    endif()
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
    if(ENABLE_ASAN)
      target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
      if(NOT target_type STREQUAL "STATIC_LIBRARY")
        target_link_options(${target} PRIVATE -fsanitize=address)
      endif()
    endif()
    if(ENABLE_UBSAN)
      target_compile_options(${target} PRIVATE -fsanitize=undefined)
      if(NOT target_type STREQUAL "STATIC_LIBRARY")
        target_link_options(${target} PRIVATE -fsanitize=undefined)
      endif()
    endif()
  elseif(ENABLE_ASAN OR ENABLE_UBSAN)
    message(FATAL_ERROR "Sanitizers are unavailable with this compiler")
  endif()
endfunction()
